name: libarchivepreload

on: workflow_dispatch

jobs:
  libarchivepreload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: make
      
      - name: Test
        run: |
          zip libarchivepreload.zip libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so LIBARCHIVEPRELOAD=libarchivepreload.zip /usr/bin/cat /mnt/perlpackarchive/libarchivepreload.c
          #LD_PRELOAD=$PWD/libarchivepreload.so LIBARCHIVEPRELOAD=libarchivepreload.zip /usr/bin/ls
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls libarchivepreload.zip
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.zip/libarchivepreload.c
          
          #LD_PRELOAD=$PWD/libarchivepreload.so LIBARCHIVEPRELOAD=libarchivepreload.zip /usr/bin/ls
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls libarchivepreload.zip
          #LD_PRELOAD=$PWD/libarchivepreload.so LIBARCHIVEPRELOAD=libarchivepreload.zip /usr/bin/cat libarchivepreload.c
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.zip/libarchivepreload.c
