name: libarchivepreload

on: workflow_dispatch

jobs:
  libarchivepreload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: make
      
      - name: Test
        run: |
          zip libarchivepreload.zip libarchivepreload.c
          
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip/
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip/libarchivepreload.c
          
          # TODO: figure out how to build .so with static zlib, maybe need to fix up fPIC relocation?
          LD_PRELOAD=$(cc --print-file-name=libz.so):$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.zip/libarchivepreload.c
          
          # not supported because it uses fstatat with a non-trivial dirfd
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/find libarchivepreload.zip
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: libarchivepreload.so
