name: libarchivepreload

on: workflow_dispatch

jobs:
  libarchivepreload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install prerequisites for xz autogen
        run: sudo apt-get install autopoint po4a gdb
      
      - name: Build
        run: make
      
      - name: Test
        run: |
          #sudo apt install ltrace && ltrace /usr/bin/find .git
          zip -r   libarchivepreload.zip    libarchivepreload.c .git
          tar -cJf libarchivepreload.tar.xz libarchivepreload.c .git
          
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.zip/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/stat libarchivepreload.zip/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/find libarchivepreload.zip
          
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.tar.xz
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.tar.xz/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.tar.xz/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/stat libarchivepreload.tar.xz/libarchivepreload.c
          LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/find libarchivepreload.tar.xz
          
          LD_PRELOAD=$PWD/libarchivepreload.so PACKFS_ARCHIVES=libarchivepreload.zip /usr/bin/cat /packfs/libarchivepreload.c
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: libarchivepreload.so
