name: libarchivepreload

on: workflow_dispatch

jobs:
  libarchivepreload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: make
      
      - name: Test
        run: |
          zip -r libarchivepreload.zip libarchivepreload.c .git
          
          sudo apt install ltrace && ltrace /usr/bin/find libarchivepreload.zip
          
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/ls -lah libarchivepreload.zip/libarchivepreload.c
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/cat libarchivepreload.zip/libarchivepreload.c
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/stat libarchivepreload.zip/libarchivepreload.c
          #LD_PRELOAD=$PWD/libarchivepreload.so /usr/bin/find libarchivepreload.zip
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: libarchivepreload.so
